[build]
  publish = "dist"
  command = "npm run build"

# Production build settings
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

# Security Headers for Production
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    
    # Content Security Policy
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' *.googleapis.com *.gstatic.com *.google-analytics.com *.googletagmanager.com;
      style-src 'self' 'unsafe-inline' *.googleapis.com *.gstatic.com;
      img-src 'self' data: blob: https: *.unsplash.com *.figma.com;
      font-src 'self' *.googleapis.com *.gstatic.com;
      connect-src 'self' *.supabase.co *.google-analytics.com *.googletagmanager.com *.doubleclick.net;
      media-src 'self' data: blob:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      frame-ancestors 'none';
      upgrade-insecure-requests;
    """
    
    # Performance & SEO
    Cache-Control = "public, max-age=31536000, immutable"
    
    # PWA Headers
    X-Robots-Tag = "index, follow, max-image-preview:large, max-snippet:-1"

# Specific cache settings for different file types
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# URL Redirects and Rewrites
[[redirects]]
  from = "/home"
  to = "/#home"
  status = 301

[[redirects]]
  from = "/about"
  to = "/#about"
  status = 301

[[redirects]]
  from = "/skills"
  to = "/#skills"
  status = 301

[[redirects]]
  from = "/journey"
  to = "/#journey"
  status = 301

[[redirects]]
  from = "/projects"
  to = "/#projects"
  status = 301

[[redirects]]
  from = "/contact"
  to = "/#contact"
  status = 301

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Edge Functions for Advanced Features
[[edge_functions]]
  function = "geolocation"
  path = "/api/geo"

# Form Handling
[forms]
  [forms.contact]
    name = "contact"

# Plugin Configuration
[[plugins]]
  package = "@netlify/plugin-lighthouse"

  [plugins.inputs.thresholds]
    performance = 0.9
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-submit-sitemap"

  [plugins.inputs]
    baseUrl = "https://www.raleskip.com"
    sitemapPath = "/sitemap.xml"
    ignorePeriod = 0
    providers = [
      "google",
      "bing"
    ]

# Environment-specific settings
[context.production]
  command = "npm run build:production"
  
[context.production.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview]
  command = "npm run build:preview"

[context.branch-deploy]
  command = "npm run build:staging"

# Functions (for API endpoints)
[functions]
  directory = "netlify/functions"

# Build processing
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true